# Site
name: 'Bl0gman'
description: 'Diary of a Blogman. Writing about all things that I read or learn about in daily life. Ideas, knowledge, quotes, technology, art, science,...'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'blogman-1'
email: 'blogman@ethnik.life'
mailchimp-list: 'https://xyz.us19.list-manage.com/subscribe?u=9a2079192369d4fa5cac97600&id=a92cf62962'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    damjan:
      name:           Damjan
      site:           damjan.carrd.co
      avatar:         /assets/images/avatar.jpg
      bio:            "Hello! My name is Damjan and I am the man behind Blogman. I hope you like my content :)"
      email:          blogman@ethnik.life
      twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: damjan
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
